export const GET_WEBINAR_REQUEST="GET_WEBINAR_REQUEST"
export const GET_WEBINAR_SUCCESS="GET_WEBINAR_SUCCESS"
export const GET_WEBINAR_FAILURE="GET_WEBINAR_FAILURE"

export const USER_REGISTER_REQUEST="USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE="USER_REGISTER_FAILURE"

export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE="USER_LOGIN_FAILURE"

export const LOGOUT_USER="LOGOUT_USER"

export const DELETE_WEBINAR_REQUEST="DELETE_WEBINAR_REQUEST"
export const DELETE_WEBINAR_SUCCESS="DELETE_WEBINAR_SUCCESS"
export const DELETE_WEBINAR_FAILURE="DELETE_WEBINAR_FAILURE"

export const ADD_WEBINAR_REQUEST="ADD_WEBINAR_REQUEST"
export const ADD_WEBINAR_SUCCESS="ADD_WEBINAR_SUCCESS"
export const ADD_WEBINAR_FAILURE="ADD_WEBINAR_FAILURE"

export const EDIT_WEBINAR_REQUEST="EDIT_WEBINAR_REQUEST"
export const EDIT_WEBINAR_SUCCESS="EDIT_WEBINAR_SUCCESS"
export const EDIT_WEBINAR_FAILURE="EDIT_WEBINAR_FAILURE"